spring.application.name=orbit

spring.datasource.url=jdbc:postgresql://localhost:5432/orbit
spring.datasource.username=postgres
spring.datasource.password=post
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=mySecretKeyForJwtThatShouldBeLongEnoughFor256BitsAndNotUsedInProduction
jwt.expiration=86400000

# Versiona CSS/JS pelo conteúdo: ao mudar o arquivo, a URL muda e o navegador não usa cache antigo
spring.web.resources.chain.strategy.content.enabled=true
spring.web.resources.chain.strategy.content.paths=/**
